### ISSUE TITLE
クラッシュ→Outlook再起動→無効化

### ISSUE THREAD

**Issue by Kaiko01** [t-miyake/OutlookOkan#53]
いつもお世話になっております。株式会社ジュパの藤原と申します。弊社では誤送信防止のため活用をさせて頂いておりますが、v2.8.0.1.1にアップデートしてから　クラッシュ→Outlook再起動→無効化が数台発生しております。ご確認ください。

Win10 or 11
M365 Outlookのデスクトップアプリ 64bit
新しいOutlookを試す　OFF

です。宜しくお願い致します。

**Comment by t-miyake** [comment]
@Kaiko01 お手数をおかけしますが、アップデート前にインストールされていたアドインのバージョンとbit数をお教えいただけないでしょうか？

**Comment by Kaiko01** [comment]
いずれも64bitですが、V2.7.2.1およびV2.8.0.1です。お手数をおかけ致します。

**Comment by Kaiko01** [comment]
ありがとうございます。クラッシュの原因表示について試してみます。

**Comment by Kaiko01** [comment]
ご連絡いただいた意図とあった表示でしょうか。クラッシュ時の表示を添付します。

![image](https://github.com/t-miyake/OutlookOkan/assets/48169611/55a6dcb6-2fcd-4d82-8a78-bd3467a05983)

**Comment by t-miyake** [comment]
@Kaiko01 説明不足で失礼いたしました。

上記の設定を行っていただくと、クラッシュした際に以下のような画面が表示されます。
この詳細として表示されるものが、詳しいエラー内容となります。(エラー内容から原因を調査することができます)
![image](https://github.com/t-miyake/OutlookOkan/assets/9583126/68a24b28-c22d-440c-8773-ed6e1caa25e1)

**Comment by s-utsugihara** [comment]
横から失礼いたします。
別原因かもしれませんが、v2.8.0.1.1のインストールで以下エラーが発生しています。
![image](https://github.com/t-miyake/OutlookOkan/assets/65207937/522e6117-e73a-46b4-bfb8-78c9e9147002)

お手数ですがご確認いただけますでしょうか。

**Comment by t-miyake** [comment]
@s-utsugihara 必要なランタイム(.NET Framework等)がインストールされていないか、もしくはアドインとOutlookのbit数が適合していない可能性が考えられます。
お手数ですが、ご利用の環境(OS等)をお教えいただけないでしょうか。

**Comment by s-utsugihara** [comment]
ご確認ありがとうございます。環境は以下の通りです。
OS：Windows 10 Pro 22H2 (64bit)
Outlook：Office2016 (32bit)

インストールしたOutlookOkanは「SafelySendMailAddin_32bit_2.8.0.1.1」です。
64bit版もインストールしてみましたが、そもそもCOMアドインとして認識されませんでした。

**Comment by s-utsugihara** [comment]
.NET Frameworkは「4.7.2」までインストールされていました。
社内で現象が出ているのが1台のみの為、環境依存の可能性が高いのですが、
解決に向けて何か試せることがあれば教えていただけると助かります。
![image](https://github.com/t-miyake/OutlookOkan/assets/65207937/1bffcff2-2464-4d34-8e67-e5528a2d9c3d)

**Comment by t-miyake** [comment]
@s-utsugihara お手数をおかけしますが、以下からダウンロードできるMS Officeのアドイン用ランタイム(最新版)を、試しにインストールしてみていただけないでしょうか。

https://www.microsoft.com/ja-JP/download/details.aspx?id=56961

※なお、恐れ入りますが、サポート対応について有償サービスとなっておりますので、特殊な事象の場合、解決までご案内できないかもしれません。

**Comment by s-utsugihara** [comment]
ありがとうございます。
MS Officeのアドイン用ランタイム(最新版)をインストールしましたが、現象変わらずでした。

因みにインストーラでインストールした場合、エラーになりますが、
ソースコードからデバッグ実行すると問題なく動作しました。

**Comment by s-utsugihara** [comment]
他アドインでも同事象が発生したため、環境依存による問題のようです。
私からの問合せについてはクローズしていただいて問題ございません。
お手数おかけいたしました。

**Comment by Kaiko01** [comment]
安定したものかクラッシュの発生も無く、[v2.8.0.1.2]のアップデートもあり、クローズさせて頂きます。ご対応をありがとうございました。
