### ISSUE TITLE
差出人変更後、送信でフリーズ

### ISSUE THREAD

**Issue by s-utsugihara** [t-miyake/OutlookOkan#54]
度々恐れ入ります。
社内のクライアントPC数百台にインストールし運用を考えております。先行して数台で検証中ですが、
差出人を共有メールアドレスに変更して送信を行うと、確認画面が表示されず、フリーズします。

OS：Windows 10 Pro 22H2 (64bit)
Outlook：Office2016 (32bit)
メールサーバー：Exchange Online
OutlookOkan：SafelySendMailAddin_32bit_2.8.0.1.1

![image](https://github.com/t-miyake/OutlookOkan/assets/65207937/f1aecdb8-9339-4587-afc0-7e0e9539f041)

**Comment by t-miyake** [comment]
@s-utsugihara ご報告ありがとうございます。本件、アドイン側の不具合と思われますので、調査のうえ、修正いたします。

**Comment by t-miyake** [comment]
@s-utsugihara 本件、修正版を更新いたしましたので、お手数をおかけしますが、ご確認くださいませ。

以下からダウンロードできます。
https://github.com/t-miyake/OutlookOkan/releases/tag/v2.8.0.1.2

**Comment by s-utsugihara** [comment]
v2.8.0.1.2にアップデート後、現象が改善されることを確認しました。
迅速な対応ありがとうございます。助かります。
